### ISSUE TITLE
Call to undefined function getMentionsFromTwt() in webmentions_send.php

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#24]
When replying to a twt, I'm getting the following error:

https://twtxt-sandbox.eapl.me/timeline/new?hash=x5rbkrq

```
Fatal error:  Uncaught Error: Call to undefined function getMentionsFromTwt() in
/sandbox.twtxt.eapl.me/timeline/partials/webmentions_send.php:4
Stack trace:
#0 /sandbox.twtxt.eapl.me/timeline/views/new_twt.php(87): include_once()
#1 /sandbox.twtxt.eapl.me/timeline/index.php(59): require('/...')
#2 {main}
  thrown in /homepages/4/d818294726/htdocs/sandbox.twtxt.eapl.me/timeline/partials/webmentions_send.php on line 4
```

**Comment by sorenpeter** [comment]
I'm getting the same error when trying to reply via my server (https://darch.dk/timeline/new?hash=x5rbkrq)

It looks like `libs/twtxt.php` is not loaded, since this is where `getMentionsFromTwt()` is defined.
